version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - data-tier

networks: 
  data-tier:
    driver: bridge

volumes:
  mongo_data: